### ISSUE TITLE
SUPERT_IRRO. Error

### ISSUE THREAD

**Issue by dkhazov** [chfenger/Nozzle#1]
Hi chfenger,
Thanks for you code! I need exactly this code for my scientific research, but...
During the execution of recompiled code the following error occurs:

forrtl: severe (408): fort: (3): Subscript #2 of the array X has value 0 which is less than the lower bound of 1

Image PC Routine Line Source
libifcoremdd.dll 0F420EF4 Unknown Unknown Unknown
SUPERT_IRRO.exe 012C9123 _MAIN__ 334 SUPERT_IRRO.f90
SUPERT_IRRO.exe 012E7722 Unknown Unknown Unknown
SUPERT_IRRO.exe 012E5B39 Unknown Unknown Unknown
SUPERT_IRRO.exe 012E5C7D Unknown Unknown Unknown
KERNEL32.DLL 75108484 Unknown Unknown Unknown
ntdll.dll 776A305A Unknown Unknown Unknown
ntdll.dll 776A302A Unknown Unknown Unknown
Press any key to continue . . .

If we look at the source code:

330 !*************************** calculate the region R and the wall location ***************
331 alpd=asin(1/M(k1,k2))
332 do k1=k4+1,Ni
333 ! first point calculation
334      x2=x(k1-1,ffn(k1-1))

So the second index of x2 array is not valid.
How to fix it?

**Comment by chfenger** [comment]
Hi, dkhazov,
Thank you for you report.
I am sorry for this bug, because this program is coded long time ago.
BUT, what can I give you a advise is "mdot", please check all mass flow rate (named with modt) in the "do k1=k4+1,Ni" loop. I guess this error may caused by mass flow balance error, because the ffn array never add a new element after jump in this loop.
May the force be with you.
And hope your good news.

> Hi chfenger,
> Thanks for you code! I need exactly this code for my scientific research, but...
> During the execution of recompiled code the following error occurs:
> 
> forrtl: severe (408): fort: (3): Subscript #2 of the array X has value 0 which is less than the lower bound of 1
> 
> Image PC Routine Line Source
> libifcoremdd.dll 0F420EF4 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012C9123 _MAIN__ 334 SUPERT_IRRO.f90
> SUPERT_IRRO.exe 012E7722 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012E5B39 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012E5C7D Unknown Unknown Unknown
> KERNEL32.DLL 75108484 Unknown Unknown Unknown
> ntdll.dll 776A305A Unknown Unknown Unknown
> ntdll.dll 776A302A Unknown Unknown Unknown
> Press any key to continue . . .
> 
> If we look at the source code:
> 
> 330 !*************************** calculate the region R and the wall location ***************
> 331 alpd=asin(1/M(k1,k2))
> 332 do k1=k4+1,Ni
> 333 ! first point calculation
> 334 x2=x(k1-1,ffn(k1-1))
> 
> So the second index of x2 array is not valid.
> How to fix it?

**Comment by chfenger** [comment]
Hi, dkhazov,
Yes, it is solved, just like I said before, this is caused by mass flow balance error.
Now, the fixed files were uploaded.
Thank you, sincerely.
May the force be with you.

> Hi chfenger,
> Thanks for you code! I need exactly this code for my scientific research, but...
> During the execution of recompiled code the following error occurs:
> 
> forrtl: severe (408): fort: (3): Subscript #2 of the array X has value 0 which is less than the lower bound of 1
> 
> Image PC Routine Line Source
> libifcoremdd.dll 0F420EF4 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012C9123 _MAIN__ 334 SUPERT_IRRO.f90
> SUPERT_IRRO.exe 012E7722 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012E5B39 Unknown Unknown Unknown
> SUPERT_IRRO.exe 012E5C7D Unknown Unknown Unknown
> KERNEL32.DLL 75108484 Unknown Unknown Unknown
> ntdll.dll 776A305A Unknown Unknown Unknown
> ntdll.dll 776A302A Unknown Unknown Unknown
> Press any key to continue . . .
> 
> If we look at the source code:
> 
> 330 !*************************** calculate the region R and the wall location ***************
> 331 alpd=asin(1/M(k1,k2))
> 332 do k1=k4+1,Ni
> 333 ! first point calculation
> 334 x2=x(k1-1,ffn(k1-1))
> 
> So the second index of x2 array is not valid.
> How to fix it?

**Comment by dkhazov** [comment]
Hi chfenger!
Thank you so much! Now it really works! Aty least for a specified conditions ))) 
Thanks again! ;-)
